name: Keep Alive

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
